version: '2'

services:
    prestashop:
        build: .\
        ports:
          - 8080:80
          - 443:443
        depends_on:
          - mariadb
        environment:
            - PS_DEV_MODE=1
            - DB_SERVER=mariadb
            - DB_USER=root
            - DB_PASSWD=admin
            - DB_NAME=prestashop
            - PS_FOLDER_ADMIN=siema
            - PS_INSTALL_AUTO=0
    mariadb:
        # image: mariadb
        build: .\db\
        # volumes:
        #   - ./docker/mariadb:/docker-entrypoint-initdb.d
        environment:
          - MYSQL_ROOT_PASSWORD=admin
          - MYSQL_DATABASE=prestashop
