version: '2'

services:
    prestashop:
        image: cos:obraz
        ports:
            - 5718:80
            - 5717:443
        environment:
            - PS_DEV_MODE=1
            - DB_SERVER=actina15.maas
            - DB_USER=be_175718
            - DB_PASSWD=pass
            - DB_NAME=be_175718
            - PS_FOLDER_ADMIN=admin
            - PS_INSTALL_AUTO=0
            - PS_ERASE_DB=0
            - PS_DOMAIN=localhost:5718
            - PS_DOMAIN_SSL=localhost:5717
        networks:
            - admin-mysql_default
        restart: always
networks:
    admin-mysql_default:
        external:
            name: admin-mysql_default
        